version: "3.7"
services:
  nginx:
    image: nginx
    ports:
      - "8010:80"
    depends_on:
      - php
    volumes:
      - "$PWD/nginx/default_ver1.conf:/etc/nginx/conf.d/default_ver1.conf"
      - "$PWD/html:/usr/share/nginx/html"
    networks:
      - app_net
    container_name: "compose-nginx"

  php:
    build: ./php
    image: php:fpm
    ports:
      - "9000:9000"
    volumes:
      - "$PWD/html:/var/www/html"
    networks:
      - app_net
    container_name: "compose-php"

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16